Fixing issues with Qt5.14 on Windows and Plugins directory.
BlueQuartzSoftware/CMP pull request #21
Opened 2021-04-21 20:38 UTC by imikejackson

Qt 5.14 allows relocatable Qt installations and so now we either need
to copy in all of the plugins from the Qt installation or just write
out a qt.conf file that points to the proper location for the Qt Plugins
directory. We chose the second option.

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

2021-04-21 21:01 UTC, JDuffeyBQ requested changes
Some of the other changes should probably also be documented.

2021-04-21 21:01 UTC, JDuffeyBQ commented on ExtLib/Qt5Support.cmake
> +          set(SUFFIX ${P_DEBUG_SUFFIX})
This will apply the debug suffix to all configurations.

2021-04-21 21:01 UTC, JDuffeyBQ commented on ExtLib/Qt5Support.cmake
> +  endif()
We could move these conditions down to their respective if statements and have an early return for APPLE.

2021-04-21 21:01 UTC, JDuffeyBQ commented on ExtLib/Qt5Support.cmake
> +      FILE(APPEND ${qt_conf_file} "Data = .\n")
```suggestion
      file(WRITE ${qt_conf_file} "[Paths]\nPlugins = ${P_QT_PLUGINS_DIR}\n")
      file(APPEND ${qt_conf_file} "Prefix = .\n")
      file(APPEND ${qt_conf_file} "LibraryExecutables = .\n")
      file(APPEND ${qt_conf_file} "Data = .\n")
```

2021-04-21 21:01 UTC, JDuffeyBQ commented on ExtLib/Qt5Support.cmake
> +    FILE(APPEND ${qt_conf_file} "Data = .\n")
```suggestion
    file(WRITE ${qt_conf_file} "[Paths]\nPlugins = ${P_QT_PLUGINS_DIR}\n")
    file(APPEND ${qt_conf_file} "Prefix = .\n")
    file(APPEND ${qt_conf_file} "LibraryExecutables = .\n")
    file(APPEND ${qt_conf_file} "Data = .\n")
```

2021-04-21 21:01 UTC, JDuffeyBQ commented on ExtLib/Qt5Support.cmake
> +    FILE(APPEND ${qt_conf_file} "Data = .\n")
```suggestion
    file(WRITE ${qt_conf_file} "[Paths]\nPlugins = ${QTPLUGINS_DIR}Plugins\n")
    file(APPEND ${qt_conf_file} "Prefix = .\n")
    file(APPEND ${qt_conf_file} "LibraryExecutables = .\n")
    file(APPEND ${qt_conf_file} "Data = .\n")
```

2021-04-22 00:17 UTC, JDuffeyBQ commented on ExtLib/Qt5Support.cmake
> +  endif()
Also since only the file itself and the plugin path change from case to case, only those need to be inside the if statements.

2021-04-22 14:12 UTC, imikejackson commented
I refactored more of the logic statements, added early returns for APPLE systems and ensured that Debug is not applied to all configurations on Visual Studio IDE builds

2021-04-22 14:42 UTC, JDuffeyBQ commented on ExtLib/Qt5Support.cmake
> +  AddQtConfTargets(QT_PLUGINS_DIR ${QM_QT_INSTALL_PLUGINS})
```suggestion
  if(NOT DREAM3D_ANACONDA)
    AddQtConfTargets(QT_PLUGINS_DIR ${QM_QT_INSTALL_PLUGINS})
  endif()
```

2021-04-22 15:03 UTC, JDuffeyBQ approved these changes

2021-04-23 12:44 UTC, imikejackson commented
Have we tested this against Qt 5.12 on Windows yet?

2021-04-23 16:51 UTC, merged